### ISSUE TITLE
Insufficent quoting in SQL query string

### ISSUE THREAD

**Issue by barryrowlingson** [banbar/Minimum_Spanning_Tree_QGIS#3]
Someone wanted to do a tree from polygons in QGIS on the GIS Stack Exchange:

https://gis.stackexchange.com/questions/368433/creating-line-connecting-polygons-points-based-on-their-location-using-qgis

and I suggested this plugin. However with their shapefile there was a "Python error - TypeError: 'NoneType' object is not iterable" error dialog and a message on the console:

```
ERROR 1: SQL Expression Parsing Error: syntax error, unexpected integer number, expecting string or identifier. Occurred around :
SELECT * FROM 0403_am_4326
              ^
```

This seems to stem from the layer name starting with a number triggering the syntax error in SQL. The SQL query is constructed here:

https://github.com/banbar/Minimum_Spanning_Tree_QGIS/blob/ea22f8034d52a4aa5b742659984823ff329b21bf/minimum_spanning_trees.py#L595

and should possibly quote its arguments:

```
query = "SELECT * FROM \"{}\"".format(name)
```

and similarly a few lines further down for `b_query`. There's a few other places where SQL queries are constructed that probably need fixing too.

Apart from that one little problem the plugin works really well and seems to have solved the users problem on the GIS Stack Exchange site.

**Comment by caliskanmurat** [comment]
Thanks for your warning. The plugin was edited and it will be updated soon.

**Comment by banbar** [comment]
Updated version is live.
